name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./website
        run: npm install

      - name: Build
        working-directory: ./website
        run: npm run build:unofficial

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --source ./website/dist --destination '$web' --account-name winterstarfallstorage --auth-mode key --overwrite

      - name: Clear Azure CDN
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name "winterstarfall-cdn-standard" --name "winterstarfall-unofficial" --resource-group "winter-starfall-resources"
